/** Realistic demo content for the OBSA team. Each person has their own voice and recurring themes. */

export type Person = {
  key: string;
  name: string;
  email: string;
  role: "admin" | "member";
  title: string;
  department: string;
  avatar: string;
  /** rating personality: base score, weekly trend, per-metric offsets */
  base: number;
  trend: number;
  offsets: Partial<Record<string, number>>;
  reliability: number; // chance a commitment gets completed
  work: [string, string, string][]; // title, what was done, impact
  wins: [string, string, string][]; // title, why it mattered, metric
  misses: [string, string, "yes" | "partially" | "no", string][]; // what, why, controllable, change
  learnings: [string, string][]; // category, content
  priorities: [string, string][]; // title, expected outcome
  stop: string[];
  start: string[];
  cont: string[];
  nonNeg: string[];
};

export const PEOPLE: Person[] = [
  {
    key: "rhea",
    name: "Rhea Kapoor",
    email: "rhea@obsa.team",
    role: "admin",
    title: "Founder & CEO",
    department: "Leadership",
    avatar: "🦄",
    base: 7.7,
    trend: 0.02,
    offsets: { communication: 0.8, efficiency: -0.6, vibe: 0.5 },
    reliability: 0.7,
    work: [
      ["Investor update — September", "Wrote and sent the monthly update to 42 angels + 3 funds.", "Two intros to seed funds came back within 48h."],
      ["Hiring: founding designer loop", "Ran 4 final-round portfolio reviews.", "Shortlist down to 2."],
      ["Q4 planning offsite", "Planned agenda, booked venue, pre-reads out.", "Team has one shared Q4 doc instead of seven."],
      ["Pricing experiment v2", "Aligned with Kabir on the 3-tier test.", "Test live on 50% of new signups."],
      ["Customer calls", "Sat in on 6 churn-risk calls.", "Found 2 accounts confused by onboarding, not price."],
      ["Board deck prep", "First draft of Q3 narrative and metrics slides.", "Draft ready a week early."],
    ],
    wins: [
      ["Closed the angel round extension", "Gives us 4 extra months of runway without a priced round.", "+$350k committed"],
      ["Offsite agenda landed", "Everyone said it was the first planning session that didn't feel like theatre.", "8/8 attended"],
      ["Two seed fund intros", "Warm intros > cold outreach. Pipeline for next raise started.", "2 first meetings booked"],
      ["Designer offer accepted", "Biggest hiring gap closed.", "Starts Oct 12"],
    ],
    misses: [
      ["Didn't block deep-work time", "Calendar got eaten by calls again.", "yes", "Block Tue/Thu mornings, no exceptions."],
      ["Board deck slipped two days", "Waited on finance numbers instead of drafting with placeholders.", "partially", "Draft with placeholders, fill later."],
      ["Too many Slack pings to the team after 9pm", "Late-night thinking leaked into everyone's evening.", "yes", "Schedule-send everything after 8pm."],
    ],
    learnings: [
      ["team", "People do their best work when the 'why' is written down, not said in a call."],
      ["process", "If a decision needs more than two meetings, it needs a doc instead."],
      ["customer", "Churn calls are 80% onboarding problems. Price is the excuse, not the reason."],
      ["execution", "My calendar is my strategy. If it's not blocked, it's not a priority."],
    ],
    priorities: [
      ["Send Q4 plan to the whole team", "One page. Everyone knows the 3 bets."],
      ["Close founding designer hire", "Signed offer by Friday."],
      ["Board meeting prep", "Deck reviewed by 2 advisors."],
      ["Start seed-round pipeline", "10 warm conversations booked."],
      ["Fix onboarding with Zoe + Arjun", "Activation plan agreed and scheduled."],
      ["1:1s with every team member", "8 conversations, notes shared."],
    ],
    stop: ["Late-night Slack", "Saying yes to every coffee chat", "Rewriting other people's docs"],
    start: ["Blocking deep-work mornings", "Writing decisions down", "Weekly customer call"],
    cont: ["Friday demos", "Monthly investor update", "Celebrating wins in #general"],
    nonNeg: ["Two deep-work mornings, calendar locked", "Every decision this week gets a written owner", "Talk to 3 customers"],
  },
  {
    key: "kabir",
    name: "Kabir Mehta",
    email: "kabir@obsa.team",
    role: "member",
    title: "Growth Lead",
    department: "Growth",
    avatar: "🚀",
    base: 7.3,
    trend: -0.12,
    offsets: { vibe: 0.7, ownership: 0.4, efficiency: -0.7, morale: -0.4 },
    reliability: 0.5,
    work: [
      ["Instagram Reels sprint", "Shipped 5 reels with Maya, tested 3 hooks.", "Best reel: 48k views, 310 signups."],
      ["Pricing experiment v2", "Set up the 3-tier test with Arjun.", "Live on 50% of traffic."],
      ["Creator partnership outreach", "DM'd 30 micro-creators in the productivity niche.", "6 replies, 2 calls booked."],
      ["Weekly growth dashboard", "Rebuilt the Looker board from scratch.", "Team stopped asking me for numbers."],
      ["Referral program landing page", "Wrote copy, waiting on design + eng.", "Not live yet."],
      ["Waitlist email sequence", "Rewrote all 4 emails.", "Open rate 41% → 52%."],
    ],
    wins: [
      ["Reel hit 48k views", "First organic content that actually drove signups, not just likes.", "310 signups"],
      ["Waitlist emails converting", "Proved copy matters more than send time.", "52% open rate"],
      ["Creator call → paid collab", "First creator deal under $500 that we can measure.", "1 deal signed"],
      ["Dashboard adopted", "Everyone uses one number now.", "0 'what's our signup number' pings"],
    ],
    misses: [
      ["Referral landing page didn't ship", "Waiting on design slots, didn't escalate early.", "partially", "Ship a no-design v0 with Webflow template."],
      ["Too many experiments at once", "Ran 5 tests, learned clearly from 1.", "yes", "Max 2 experiments per week."],
      ["Skipped the Tuesday growth sync", "Thought it was low value; team lost context.", "yes", "Keep it, make it 15 minutes."],
      ["Paid ads budget overspent", "Didn't set daily caps on the new campaign.", "yes", "Daily caps on every campaign, day one."],
    ],
    learnings: [
      ["customer", "Our best users find us through a friend, not an ad. Referral is the channel."],
      ["execution", "Waiting on others is a decision. If it's blocked for 2 days, escalate."],
      ["process", "An experiment without a written hypothesis isn't an experiment, it's a vibe."],
      ["product", "Hooks that name the pain ('Sunday scaries?') beat feature hooks 3:1."],
    ],
    priorities: [
      ["Ship referral program landing page", "Live page, tracking referrals end-to-end."],
      ["Launch creator collab #2", "2 creators posting, tracked links."],
      ["Pricing test readout", "Decision memo: keep, kill, or iterate."],
      ["Reels: 5 more with the winning hook", "Find if the 48k was luck or a pattern."],
      ["Cut CAC on paid by 20%", "New creative + caps live."],
      ["Write growth playbook v1", "Doc the 3 channels that work."],
    ],
    stop: ["Running 5 experiments at once", "Waiting silently on blockers", "Checking dashboards every hour"],
    start: ["Escalating blockers after 48h", "Writing hypotheses first", "Shipping ugly v0s"],
    cont: ["Reels with Maya", "Creator outreach", "Weekly growth readout"],
    nonNeg: ["Referral page live, ugly is fine", "Two experiments max", "Escalate anything blocked >48h"],
  },
  {
    key: "zoe",
    name: "Zoe Okafor",
    email: "zoe@obsa.team",
    role: "member",
    title: "Product Designer",
    department: "Design",
    avatar: "🎨",
    base: 7.8,
    trend: 0.1,
    offsets: { work: 0.6, execution: 0.4, communication: 0.3 },
    reliability: 0.8,
    work: [
      ["Onboarding redesign", "3-screen flow with progress, tested with 5 users.", "Task completion 3/5 → 5/5."],
      ["Design system tokens", "Moved colors + type to tokens, synced with Arjun.", "Dark mode basically free now."],
      ["Reels templates for Maya", "Built 4 reusable Figma frames.", "Cut reel production time in half."],
      ["Referral page mocks", "Two directions, one mobile-first.", "Ready for eng."],
      ["Usability sessions", "Ran 5 remote tests on the weekly view.", "Found 3 confusing labels."],
      ["App icon refresh", "Explored 12 directions, narrowed to 2.", "Team vote Friday."],
    ],
    wins: [
      ["Onboarding test went 5/5", "First time every tester finished without help.", "100% completion"],
      ["Design tokens shipped", "Engineering and design finally speak the same language.", "120 hardcoded colors removed"],
      ["Templates saved Maya a day", "Design that multiplies someone else's output.", "~6h saved/week"],
    ],
    misses: [
      ["Over-polished the icon exploration", "Spent 2 days on something that needed 4 hours.", "yes", "Timebox explorations, show at 50%."],
      ["Referral mocks late for Kabir", "Didn't know it was urgent — it wasn't in my priorities.", "partially", "Ask growth for their top 3 every Monday."],
      ["Skipped writing test notes", "Insights lived in my head for 3 days.", "yes", "Notes in Notion same day."],
    ],
    learnings: [
      ["customer", "Users don't read. If the label needs explaining, the label is wrong."],
      ["process", "Show work at 50%. Feedback at 90% is just politeness."],
      ["product", "Progress indicators make long flows feel short."],
      ["team", "Pairing with eng for one hour saves three rounds of handoff."],
    ],
    priorities: [
      ["Onboarding v2 into build", "Specs handed off, Arjun unblocked."],
      ["Referral page final design", "Kabir can ship by Thursday."],
      ["Weekly view usability fixes", "3 confusing labels fixed."],
      ["Design system: components pass", "Buttons, inputs, cards tokenized."],
      ["Mentor the new designer onboarding plan", "30-60-90 doc ready."],
      ["Icon: final direction", "Team-voted icon exported."],
    ],
    stop: ["Polishing explorations", "Designing in isolation", "Skipping notes"],
    start: ["Showing work at 50%", "Monday priority check with growth", "Same-day test notes"],
    cont: ["Weekly usability tests", "Pairing with Arjun", "Template work for content"],
    nonNeg: ["Show every design at 50% first", "Onboarding specs to eng by Wednesday", "One usability session"],
  },
  {
    key: "arjun",
    name: "Arjun Nair",
    email: "arjun@obsa.team",
    role: "member",
    title: "Founding Engineer",
    department: "Engineering",
    avatar: "⚡",
    base: 8.0,
    trend: 0.03,
    offsets: { efficiency: 0.8, execution: 0.7, communication: -1.4, vibe: -0.3 },
    reliability: 0.75,
    work: [
      ["Auth migration", "Moved sessions to the new provider with zero downtime.", "0 logged-out users."],
      ["Pricing test infra", "Feature flags + experiment assignment service.", "Growth can run tests without me."],
      ["Onboarding v2 build", "Built screens 1–2, wired analytics.", "Behind flag, internal testing."],
      ["Perf: dashboard load", "Killed 3 N+1 queries.", "P95 2.4s → 600ms."],
      ["On-call rotation setup", "PagerDuty + runbooks for top 5 alerts.", "Dev can cover weekends."],
      ["Referral tracking backend", "Link generation + attribution tables.", "Ready for frontend."],
    ],
    wins: [
      ["Dashboard P95 under 1s", "Biggest complaint in user calls, fixed.", "2.4s → 0.6s"],
      ["Zero-downtime auth migration", "Risky migration, nobody noticed. That's the goal.", "0 incidents"],
      ["Experiment infra self-serve", "Unblocked growth permanently.", "3 tests launched without eng"],
    ],
    misses: [
      ["Didn't post updates in #eng", "Heads down, forgot the team needs to know what's shipping.", "yes", "End-of-day one-liner in #eng."],
      ["Underestimated onboarding v2", "Assumed design was final; it wasn't.", "partially", "Kickoff with Zoe before estimating."],
      ["Weekend deploy broke webhooks", "Skipped staging because it was 'small'.", "yes", "No-staging-no-deploy rule. Even small."],
    ],
    learnings: [
      ["execution", "Estimates are fiction until design is final. Estimate after kickoff."],
      ["team", "If I don't say what I shipped, it didn't happen for anyone else."],
      ["process", "Small deploys break things too. Staging every time."],
      ["product", "Speed is a feature. Users noticed the dashboard before we told them."],
    ],
    priorities: [
      ["Onboarding v2 shipped to 100%", "Flag removed, activation tracked."],
      ["Referral tracking end-to-end", "Kabir can see referrals in dashboard."],
      ["Write architecture doc for new hires", "Dev and next hire ramp faster."],
      ["Error budget + alerting", "Top 5 alerts with runbooks."],
      ["Daily #eng updates", "One line every day."],
      ["DB backups tested", "Restore drill done, documented."],
    ],
    stop: ["Deploying on Fridays", "Silent heads-down weeks", "Estimating before kickoff"],
    start: ["Daily #eng one-liners", "Staging for every deploy", "Pairing with Zoe on specs"],
    cont: ["Perf work", "Self-serve tooling for growth", "Code reviews within 24h"],
    nonNeg: ["Post a one-liner in #eng every day", "No deploy without staging", "Ship onboarding v2"],
  },
  {
    key: "maya",
    name: "Maya Lindqvist",
    email: "maya@obsa.team",
    role: "member",
    title: "Content Lead",
    department: "Content",
    avatar: "✍️",
    base: 6.7,
    trend: 0.15,
    offsets: { vibe: 0.9, morale: 0.5, efficiency: -0.6 },
    reliability: 0.6,
    work: [
      ["Newsletter #14: 'The Sunday Reset'", "Wrote, edited, sent to 8.2k.", "47% open, 6% click."],
      ["Reels with Kabir", "Scripted + shot 5 reels.", "Top one 48k views."],
      ["Blog: 'Why we reset every week'", "Founder-voice essay with Rhea.", "Top post of the month, 3.1k reads."],
      ["Content calendar Q4", "Mapped 12 weeks of themes.", "Team can plan around it."],
      ["Community AMA", "Hosted a 45-min AMA in Discord.", "120 live, 40 questions."],
      ["Case study: early user", "Interviewed and drafted.", "Waiting on approval."],
    ],
    wins: [
      ["Reset essay went semi-viral", "Shared by 2 founders with big audiences. It's our story now.", "3.1k reads, 180 signups"],
      ["AMA turnout", "Proved the community is real, not lurkers.", "120 live"],
      ["Newsletter click rate record", "Shorter format worked.", "6% CTR"],
    ],
    misses: [
      ["Case study stuck in approval", "Sent it to the customer without a deadline.", "partially", "Always ask for approval by a date."],
      ["Posted 2 of 5 planned LinkedIn posts", "Ran out of time after reels took longer.", "yes", "Batch-write LinkedIn on Monday."],
      ["Missed newsletter Tuesday slot", "Editing loop with Rhea took 3 rounds.", "partially", "Agree outline before drafting."],
    ],
    learnings: [
      ["customer", "Our audience shares honesty, not polish. Behind-the-scenes beats announcements."],
      ["execution", "Batching beats daily inspiration. Write 5 when you write 1."],
      ["process", "Outline sign-off first saves two rounds of edits."],
      ["team", "Kabir's data + my words = content that performs. Pair more."],
    ],
    priorities: [
      ["Newsletter #15 sent on Tuesday", "On time, outline approved Monday."],
      ["Publish case study", "Live on blog + LinkedIn."],
      ["5 LinkedIn posts batched", "Scheduled by Monday noon."],
      ["Reels round 2 with Kabir", "5 reels using winning hook."],
      ["Launch community challenge", "'Reset streak' challenge in Discord."],
      ["Q4 content calendar shared", "Everyone knows what's shipping."],
    ],
    stop: ["Writing posts one by one", "Sending drafts without outlines", "Open-ended approvals"],
    start: ["Monday batching", "Outline sign-off", "Approval deadlines"],
    cont: ["Reels with Kabir", "Honest founder-voice posts", "Community AMAs"],
    nonNeg: ["Newsletter out Tuesday 9am", "Batch LinkedIn Monday", "Publish the case study"],
  },
  {
    key: "dev",
    name: "Dev Sharma",
    email: "dev@obsa.team",
    role: "member",
    title: "Backend Engineer",
    department: "Engineering",
    avatar: "🛠️",
    base: 7.4,
    trend: -0.18,
    offsets: { work: 0.3, morale: -0.8, vibe: -0.6, communication: -0.4 },
    reliability: 0.55,
    work: [
      ["Notifications service", "Email + push queue with retries.", "Reminder emails ready to wire."],
      ["Billing webhooks", "Stripe webhook handlers + idempotency.", "Double-charge bug gone."],
      ["Data export endpoint", "CSV export for team admins.", "Top enterprise ask, done."],
      ["Bug bash", "Closed 14 bugs from the backlog.", "Backlog 61 → 47."],
      ["On-call weekend", "Covered two incidents.", "Both resolved < 30 min."],
      ["API rate limiting", "Token-bucket limiter on public API.", "Stopped the scraper."],
    ],
    wins: [
      ["Double-charge bug fixed", "Was costing us trust with paying users.", "0 refunds this week"],
      ["Export endpoint shipped", "Enterprise lead said it unblocks their pilot.", "1 pilot unblocked"],
      ["Incident response < 30 min", "On-call setup works.", "2 incidents, 2 fast fixes"],
    ],
    misses: [
      ["Notifications service slipped", "Too much context-switching to bugs.", "partially", "Protect 2 days for project work."],
      ["Didn't ask for help on queue design", "Spent a day stuck alone.", "yes", "Ask after 1 hour stuck."],
      ["Burnt out after on-call weekend", "No recovery day after weekend incidents.", "partially", "Take Monday off after on-call weekends."],
    ],
    learnings: [
      ["execution", "Stuck for an hour = ask. Pride costs more than the question."],
      ["process", "Bug days and project days can't be the same days."],
      ["team", "On-call needs recovery time built in or it compounds."],
      ["product", "Admins care about export more than dashboards. Give them their data."],
    ],
    priorities: [
      ["Notifications service live", "Reminder emails sending."],
      ["Rate limiting on all public routes", "No unthrottled endpoints."],
      ["Bug backlog under 40", "Ruthless triage."],
      ["Write on-call recovery policy", "Approved by Rhea."],
      ["Pair with Arjun on queue design", "Design reviewed."],
      ["Billing reconciliation script", "Weekly report automated."],
    ],
    stop: ["Context-switching every hour", "Suffering in silence when stuck", "Weekend Slack checking"],
    start: ["Asking after 1 hour stuck", "Protected project days", "Recovery days after on-call"],
    cont: ["Fast incident response", "Bug bashes", "Idempotent everything"],
    nonNeg: ["Ship notifications service", "Ask for help within an hour", "One full offline day"],
  },
  {
    key: "tara",
    name: "Tara Fernandes",
    email: "tara@obsa.team",
    role: "member",
    title: "Ops & Community",
    department: "Ops",
    avatar: "🌀",
    base: 7.5,
    trend: 0.04,
    offsets: { ownership: 0.6, communication: 0.5, efficiency: 0.2 },
    reliability: 0.75,
    work: [
      ["Offsite logistics", "Venue, food, travel for 8.", "Under budget by 12%."],
      ["Support inbox zero", "Answered 64 tickets, wrote 6 macros.", "First response 9h → 2h."],
      ["Discord moderation setup", "Roles, rules, 2 volunteer mods.", "Spam down to zero."],
      ["Vendor contracts review", "Renegotiated 3 SaaS tools.", "Saving $410/month."],
      ["New-hire onboarding kit", "Laptop, accounts, first-week plan.", "Designer day 1 sorted."],
      ["Help center articles", "Wrote 8 articles from top tickets.", "Ticket volume -18%."],
    ],
    wins: [
      ["Support first response under 2h", "Users noticed. Two tweeted about it.", "9h → 2h"],
      ["$410/mo saved on tools", "Runway is a feature too.", "$4.9k/yr"],
      ["Help center cut tickets", "Self-serve works if the articles are real answers.", "-18% tickets"],
    ],
    misses: [
      ["Help center search is still bad", "Picked the cheapest tool without testing search.", "yes", "Trial before buying, always."],
      ["Didn't escalate the bug pattern", "Saw 9 tickets on same bug, didn't flag eng.", "yes", "Flag any 3+ ticket pattern same day."],
      ["Offsite dietary list incomplete", "Assumed instead of asking.", "yes", "Form, not assumptions."],
    ],
    learnings: [
      ["customer", "Tickets are a product roadmap in disguise. Tag them."],
      ["process", "Macros save time only if you update them monthly."],
      ["team", "A form beats a Slack thread for anything with more than 4 answers."],
      ["execution", "Trial everything before committing — cheap tools get expensive."],
    ],
    priorities: [
      ["Weekly ticket-pattern report to eng", "Top 3 patterns flagged every Friday."],
      ["Help center search fix", "Search returns the right article for top 10 queries."],
      ["Designer onboarding week", "Day 1–5 plan executed."],
      ["Community 'reset streak' with Maya", "Launch + 50 participants."],
      ["Q4 ops budget", "Budget doc approved."],
      ["Support macros refresh", "All macros reviewed."],
    ],
    stop: ["Assuming instead of asking", "Sitting on ticket patterns", "Buying without trials"],
    start: ["Friday ticket-pattern report", "Forms for logistics", "Trials before purchases"],
    cont: ["Inbox zero daily", "Vendor renegotiations", "Help center writing"],
    nonNeg: ["Ticket-pattern report every Friday", "Inbox zero daily", "Onboard the designer flawlessly"],
  },
  {
    key: "leo",
    name: "Leo Martins",
    email: "leo@obsa.team",
    role: "member",
    title: "Partnerships",
    department: "Growth",
    avatar: "🤝",
    base: 6.4,
    trend: 0.14,
    offsets: { vibe: 0.6, ownership: -0.5, execution: -0.4 },
    reliability: 0.5,
    work: [
      ["University pilot outreach", "Pitched 8 student orgs.", "2 pilots in discussion."],
      ["Integration partner: Notion templates", "Built 3 templates with our reset flow.", "Listed in gallery."],
      ["Co-working space partnerships", "Visited 3 spaces, pitched team plans.", "1 trial starting."],
      ["Partner one-pager", "Wrote deck + one-pager.", "Used in 5 pitches."],
      ["CRM cleanup", "Deduped and tagged 400 contacts.", "Pipeline is real now."],
      ["Event: founder breakfast", "Co-hosted with a local VC.", "22 founders, 6 leads."],
    ],
    wins: [
      ["Notion gallery listing", "Free distribution in front of exactly our users.", "1.2k template duplicates"],
      ["University pilot verbal yes", "First institutional customer path.", "1 verbal yes"],
      ["Founder breakfast leads", "Warm leads, not cold lists.", "6 leads"],
    ],
    misses: [
      ["Didn't follow up within 24h", "Let 4 warm leads go cold over the weekend.", "yes", "Follow-ups same day, templated."],
      ["Pipeline review skipped", "No fixed time for it.", "yes", "Friday 4pm pipeline review."],
      ["Over-promised custom features to a partner", "Wanted the yes too much.", "yes", "Check with Arjun before promising product."],
    ],
    learnings: [
      ["customer", "Student orgs move fast but need a champion. Find the champion first."],
      ["execution", "Follow-up speed is the whole job."],
      ["process", "A CRM is only useful if you review it weekly."],
      ["team", "Ask product before promising. Partners remember promises."],
    ],
    priorities: [
      ["Sign first university pilot", "Signed agreement."],
      ["Follow up all breakfast leads", "6 follow-ups, 3 calls."],
      ["Partner pipeline review ritual", "Every Friday 4pm."],
      ["Co-working trial live", "10 members using OBSA."],
      ["Second Notion template pack", "3 more templates."],
      ["Partner FAQ", "Answers the top 10 partner questions."],
    ],
    stop: ["Over-promising", "Letting leads cool", "Skipping pipeline review"],
    start: ["Same-day follow-ups", "Friday pipeline review", "Checking with product first"],
    cont: ["Events", "Template distribution", "University outreach"],
    nonNeg: ["Every lead followed up within 24h", "Friday pipeline review", "Sign the pilot"],
  },
];

export const REVIEW_COMMENTS = {
  kudos: [
    "This is the energy. The way you owned the miss is exactly the culture we want.",
    "Huge week. Love that the win has a number attached.",
    "Clean reset. Priorities are sharp and realistic.",
  ],
  reviewed: [
    "Solid. Let's talk about the blocked item in our 1:1.",
    "Good honesty on the misses. The correction is the right one.",
    "Read it. Agree with the stop/start — hold yourself to it.",
    "Nice. Make sure the non-negotiable is visible to the team.",
  ],
  needs_attention: [
    "Morale dipped two weeks in a row. Let's grab 20 minutes — not a performance thing, a human thing.",
    "Same commitment carried three weeks. Either we kill it or we unblock it this week. Your call, let's decide together.",
  ],
};
